import type { Metadata } from "next";
import { Barlow, Fraunces } from "next/font/google";

import Footer from "@/components/Navigation/Footer";
import Header from "@/components/Navigation/Header";

import "./globals.css";

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  weight: ["700", "800", "900"],
});

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fraunces.variable} ${barlow.variable} bg-[#F2F2F2] antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
